На проверку
Даниил, добрый вечер, выкладываю экзаменационную работу но, к сожалению, столкнулся с проблемой на которую потратил более 10 часов, но так и не смог решить:

ant -f /Users/andrejzigula/NetBeansProjects/exam-toxedomoon/WEApp/WEApp-ejb -Dnb.internal.action.name=rebuild "-Duser.properties.file=/Users/andrejzigula/Library/Application Support/NetBeans/10.0/build.properties" clean dist
init:
undeploy-clean:
deps-clean:
Deleting directory /Users/andrejzigula/NetBeansProjects/exam-toxedomoon/WEApp/WEApp-ejb/build
clean:
init:
deps-jar:
Created dir: /Users/andrejzigula/NetBeansProjects/exam-toxedomoon/WEApp/WEApp-ejb/build/classes
Copying 2 files to /Users/andrejzigula/NetBeansProjects/exam-toxedomoon/WEApp/WEApp-ejb/build/classes/META-INF
Created dir: /Users/andrejzigula/NetBeansProjects/exam-toxedomoon/WEApp/WEApp-ejb/build/empty
Created dir: /Users/andrejzigula/NetBeansProjects/exam-toxedomoon/WEApp/WEApp-ejb/build/generated-sources/ap-source-output
Compiling 4 source files to /Users/andrejzigula/NetBeansProjects/exam-toxedomoon/WEApp/WEApp-ejb/build/classes
warning: Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor' less than -source '8'
Note: Creating static metadata factory ...
1 warning

An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.NoClassDefFoundError: javax/annotation/Generated
	at org.eclipse.persistence.internal.jpa.modelgen.MetadataMirrorFactory.setEnvironments(MetadataMirrorFactory.java:327)
	at org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor.process(CanonicalModelProcessor.java:368)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:977)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:893)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1219)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1331)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
	at com.sun.tools.javac.main.Main.compile(Main.java:311)
	at com.sun.tools.javac.main.Main.compile(Main.java:170)
	at com.sun.tools.javac.Main.compile(Main.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:57)
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1404)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1133)
	at org.netbeans.modules.java.source.ant.JavacTask.execute(JavacTask.java:120)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.base/java.util.Vector.forEach(Vector.java:1387)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:391)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.module.bridge.impl.BridgeImpl.run(BridgeImpl.java:261)
	at org.apache.tools.ant.module.run.TargetExecutor.run(TargetExecutor.java:574)
	at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:128)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 49 more
BUILD FAILED (total time: 1 second)